# Generated by Django 5.2.9 on 2025-12-08 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_mensaje_autoatencion'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto (ej: 19.00 para 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['empresa', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ProductoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_impuestos', to='impuestos.impuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_impuestos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto-Impuesto',
                'verbose_name_plural': 'Productos-Impuestos',
                'ordering': ['producto', 'orden'],
                'unique_together': {('producto', 'impuesto')},
            },
        ),
    ]
