# Generated by Django 5.2.9 on 2025-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambio_password_obligatorio',
            field=models.BooleanField(default=False, verbose_name='Cambio de contraseña obligatorio'),
        ),
    ]
