# Generated by Django 5.0 on 2025-12-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('impuesto', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Impuesto (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='productos_p_empresa_264f06_idx'), models.Index(fields=['tipo'], name='productos_p_tipo_77adae_idx')],
            },
        ),
    ]
