# Generated by Django 5.2.9 on 2025-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuestos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='impuesto',
        ),
        migrations.AddField(
            model_name='producto',
            name='impuestos',
            field=models.ManyToManyField(blank=True, related_name='productos', through='impuestos.ProductoImpuesto', to='impuestos.impuesto'),
        ),
    ]
