# Generated by Django 5.2.9 on 2025-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_impuesto_producto_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único del producto', max_length=50, null=True, verbose_name='SKU'),
        ),
    ]
