# Generated by Django 5.2.9 on 2025-12-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('PRODUCTO', 'Producto'), ('COTIZACION', 'Cotización')], max_length=20)),
                ('entidad_id', models.IntegerField(help_text='ID del objeto a modificar')),
                ('datos_propuestos', models.JSONField(help_text='Datos completos propuestos para la entidad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('resolutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio',
                'verbose_name_plural': 'Solicitudes de Cambio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
