# Generated by Django 5.2.9 on 2025-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
    ]
