# Generated by Django 5.0 on 2025-12-07 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'estado'], name='cotizacione_empresa_eb156b_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='cotizacione_cliente_b0cc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_creacion'], name='cotizacione_fecha_c_1e3b4e_idx'),
        ),
    ]
