# Generated by Django 5.2.9 on 2025-12-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='canal_preferencia',
            field=models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10, verbose_name='Canal de preferencia'),
        ),
    ]
