# Generated by Django 5.2.9 on 2025-12-08 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_canal_preferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
