# Generated by Django 5.2.9 on 2025-12-08 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
