# Generated by Django 5.2.9 on 2025-12-09 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_cotizacion_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='es_decision_automatica',
            field=models.BooleanField(default=False, verbose_name='Decisión Automática'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_decision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de decisión'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_cotizacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Decisión'),
        ),
    ]
