# Generated by Django 5.2.9 on 2025-12-09 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_cotizacion_es_decision_automatica_and_more'),
        ('empresas', '0005_empresa_mensajeria_automatica_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaOfertaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de ejecución (1 = primera oferta, 2 = segunda...)', verbose_name='Orden')),
                ('tiempo_espera_valor', models.PositiveIntegerField(verbose_name='Tiempo de espera')),
                ('tiempo_espera_unidad', models.CharField(choices=[('HORAS', 'Horas'), ('DIAS', 'Días')], default='HORAS', max_length=10, verbose_name='Unidad (Espera)')),
                ('descuento_porcentaje', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porcentaje Descuento')),
                ('tiempo_validez_valor', models.PositiveIntegerField(verbose_name='Tiempo de validez')),
                ('tiempo_validez_unidad', models.CharField(choices=[('HORAS', 'Horas'), ('DIAS', 'Días')], default='DIAS', max_length=10, verbose_name='Unidad (Validez)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_oferta', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Regla de Oferta Automática',
                'verbose_name_plural': 'Reglas de Oferta Automática',
                'ordering': ['orden'],
                'unique_together': {('empresa', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='OfertaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('descuento_porcentaje', models.PositiveIntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('ACEPTADA', 'Aceptada')], default='ACTIVA', max_length=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_automaticas', to='cotizaciones.cotizacion')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizaciones.reglaofertaautomatica')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
