# Generated by Django 5.2.9 on 2025-12-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_reglaofertaautomatica_ofertacotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaofertaautomatica',
            name='tiempo_espera_unidad',
            field=models.CharField(choices=[('MINUTOS', 'Minutos'), ('HORAS', 'Horas'), ('DIAS', 'Días')], default='HORAS', max_length=10, verbose_name='Unidad (Espera)'),
        ),
        migrations.AlterField(
            model_name='reglaofertaautomatica',
            name='tiempo_validez_unidad',
            field=models.CharField(choices=[('MINUTOS', 'Minutos'), ('HORAS', 'Horas'), ('DIAS', 'Días')], default='DIAS', max_length=10, verbose_name='Unidad (Validez)'),
        ),
    ]
