# Generated by Django 5.2.9 on 2025-12-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mensaje_autoatencion',
            field=models.TextField(blank=True, help_text='Mensaje que se mostrará en el portal de autoatención', verbose_name='Mensaje Autoatención'),
        ),
    ]
