# Generated by Django 5.2.9 on 2025-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_mensaje_autoatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='autoaprobar_cotizaciones',
            field=models.BooleanField(default=False, help_text='Aprobar automáticamente cotizaciones recibidas por autoatención', verbose_name='Auto-aprobar Cotizaciones'),
        ),
    ]
