# Generated by Django 5.2.9 on 2025-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_autoaprobar_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mensaje_correo_cotizacion',
            field=models.TextField(blank=True, help_text='Mensaje personalizado para el cuerpo del correo de la cotización', verbose_name='Mensaje Correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensaje_whatsapp_cotizacion',
            field=models.TextField(blank=True, help_text='Mensaje personalizado para el envío por WhatsApp', verbose_name='Mensaje WhatsApp'),
        ),
    ]
