# Generated by Django 5.2.9 on 2025-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_mensaje_correo_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mensajeria_automatica_activa',
            field=models.BooleanField(default=False, help_text='Habilitar envío automático de ofertas/fidelización', verbose_name='Mensajería Automática Activa'),
        ),
    ]
